defaults:
  - driver: ppo_acmpc
  - driver/ppo/policy: xtma_beta_acmpc
  - driver/ppo/training: ppo
  - driver/ppo/obs_configs: birdview_chauffeurnet+bev
  - train_envs: endless_debug
actors:
  hero:
    driver: ppo_acmpc
    reward:
      entry_point: reward.valeo_action:ValeoAction
      kwargs: {}
    terminal:
      entry_point: terminal.valeo_no_det_px:ValeoNoDetPx
      kwargs: {}
ev_id: hero
carla_sh_path: /home/ubuntu/apps/carla/carla910/CarlaUE4.sh
total_timesteps: 1e8
seed: 2021
kill_running: true
dummy: false
wb_project: train_rl
wb_name: null
wb_notes: null
wb_tags: null
curriculum: false
