entry_point: agents.cilrs.cilrs_agent:CilrsAgent
ckpt: null
wb_run_path: null
wb_ckpt_step: null
rl_run_path: zhejun/ppo_dec/xghmsngp
rl_ckpt_step: 8183808
env_wrapper:
  entry_point: agents.cilrs.cilrs_wrapper:CilrsWrapper
  kwargs:
    acc_as_action: true
    view_augmentation: false
    value_as_supervision: true
    value_factor: 1.0
    action_distribution: beta_shared
    dim_features_supervision: 256
    input_states:
    - speed
    - vec
    - cmd
    im_mean:
    - 0.485
    - 0.456
    - 0.406
    im_std:
    - 0.229
    - 0.224
    - 0.225
    im_stack_idx:
    - -1
policy:
  entry_point: agents.cilrs.models.cilrs_model:CoILICRA
  kwargs:
    freeze_value_head: false
    freeze_action_head: false
    resnet_pretrain: true
    perception_output_neurons: 1000
    measurements_neurons:
    - 128
    - 128
    measurements_dropouts:
    - 0.0
    - 0.0
    join_neurons:
    - 512
    - 512
    - 256
    join_dropouts:
    - 0.0
    - 0.0
    - 0.0
    speed_branch_neurons:
    - 256
    - 256
    speed_branch_dropouts:
    - 0.0
    - 0.5
    value_branch_neurons:
    - 256
    - 256
    value_branch_dropouts:
    - 0.0
    - 0.5
    number_of_branches: 1
    branches_neurons:
    - 256
    - 256
    branches_dropouts:
    - 0.0
    - 0.5
    squash_outputs: false
    perception_net: resnet34
training:
  entry_point: agents.cilrs.models.trainer:Trainer
  kwargs:
    batch_size: 48
    num_workers: 4
    learning_rate: 0.0002
    lr_schedule_factor: 0.5
    branch_weights:
    - 1.0
    action_weights:
    - 0.5
    - 0.5
    speed_weight: 0.05
    value_weight: 0.001
    features_weight: 0.05
    l1_loss: true
    action_kl: true
    action_agg: null
    action_mll: null
    starting_iteration: 0
    starting_epoch: 0
    im_augmentation: hard
obs_configs:
  speed:
    module: actor_state.speed
  gnss:
    module: navigation.gnss
  central_rgb:
    module: camera.rgb
    fov: 100
    width: 900
    height: 256
    location:
    - -1.5
    - 0.0
    - 2.0
    rotation:
    - 0.0
    - 0.0
    - 0.0
  route_plan:
    module: navigation.waypoint_plan
    steps: 20
  birdview:
    module: birdview.chauffeurnet
    width_in_pixels: 192
    pixels_ev_to_bottom: 40
    pixels_per_meter: 5.0
    history_idx:
    - -16
    - -11
    - -6
    - -1
    scale_bbox: false
