adapter:
  config:
    actors:
      hero:
        driver: ppo
        reward:
          entry_point: reward.valeo_action:ValeoAction
        terminal:
          entry_point: terminal.leaderboard:Leaderboard
    driver:
      ppo:
        entry_point: agents.cilrs.cilrs_agent:CilrsAgent
        env_wrapper:
          entry_point: agents.cilrs.cilrs_wrapper:CilrsWrapper
          kwargs:
            acc_as_action: true
            input_states:
            - control
            - vel_xy
        wb_ckpt_step: null
        wb_run_path: iccv21-roach/trained-models/21trg553
  type: roach
cost:
  config:
    decay_factor: 0.999
    image_height: 256
    image_width: 256
    lateral_offset: 0.5
    lateral_scaler: 0.75
    lateral_speed_offset: 0.0
    lateral_speed_scaler: 0.1
    longitudinal_offset: 0.5
    longitudinal_scaler: 0.75
    longitudinal_speed_offset: 0.0
    longitudinal_speed_scaler: 1.0
    mask_alpha: 1.0
    pixels_per_meter: 10
    reduction: sum
    vehicle_length: 5.0
    vehicle_width: 2.0
  type: extended_bev_with_pedestrian
environment:
  action_repeat: 1
  bevs:
  - config:
      crop_type: FRONT_AREA_ONLY
      height: 256
      lane_marking_thickness: 2
      light_circle: true
      pixels_per_meter: 10
      render_lanes_on_junctions: false
      road_light: true
      road_on_off: true
      width: 256
    id: bev_world
  driver: external
  fixed_delta_seconds: 0.1
  max_steps: 5000
  name: carla_env_leaderboard
  port: 2000
  renderer:
    background_color:
    - 0
    - 0
    - 0
    channel: 3
    create_date_time_path: true
    cursor:
    - 0
    - 0
    font_color:
    - 255
    - 255
    - 255
    font_scale: 0.25
    font_thickness: 1
    height: 1280
    name: MPC Leaderboard Evaluation
    save: true
    save_path: figures/env_debug/eval_mpc_leaderboard/routes_testing_town_02_roach_mpc_situational/Town02_route5
    show: true
    width: 6000
  route: null
  sensors:
  - config: {}
    id: ego
    type: VehicleSensor
  - config: {}
    id: sit
    type: SituationSensor
  - config: {}
    id: col
    type: CollisionSensor
  tasks:
  - num_vehicles:
    - 60
    - 90
    world: Town02
  tm_port: 8000
evaluator:
  action_size: 2
  adapter_weight: 0.0
  batch_size: 1
  bev_agent_channel: 7
  bev_calculate_offroad: false
  bev_selected_channels:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 10
  - 11
  bev_vehicle_channel: 6
  cost_weight:
    DRIVE:
      acceleration_jerk: 1.0
      action_difference: 1000.0
      ego_location_l1: 5000.0
      ego_speed_l1: 0.0
      ego_yaw_l1: 0.0
      lane_cost: 1.0
      offroad_cost: 10.0
      pedestrian_cost: 1000.0
      road_cost: -1.0
      road_green_cost: -1.0
      road_off_cost: 10.0
      road_on_cost: -1.0
      road_red_yellow_cost: 0.0
      steer_jerk: 1.0
      vehicle_cost: 1000.0
    JUNCTION:
      acceleration_jerk: 1.0
      action_difference: 100.0
      ego_location_l1: 20000.0
      ego_speed_l1: 0.0
      ego_yaw_l1: 0.0
      lane_cost: 1.0
      offroad_cost: 100.0
      pedestrian_cost: 1000.0
      road_cost: -1.0
      road_green_cost: -1.0
      road_off_cost: 1.0
      road_on_cost: -1.0
      road_red_yellow_cost: 0.0
      steer_jerk: 0.0
      vehicle_cost: 1000.0
    STEER:
      acceleration_jerk: 100.0
      action_difference: 100.0
      ego_location_l1: 10000.0
      ego_speed_l1: 0.0
      ego_yaw_l1: 0.0
      lane_cost: 1.0
      offroad_cost: 10.0
      pedestrian_cost: 1000.0
      road_cost: -1.0
      road_green_cost: -10.0
      road_off_cost: 100.0
      road_on_cost: -10.0
      road_red_yellow_cost: 0.0
      steer_jerk: 1000000.0
      vehicle_cost: 1000.0
    STOP:
      acceleration_jerk: 100.0
      action_difference: 100.0
      ego_location_l1: 10000.0
      ego_speed_l1: 0.0
      ego_yaw_l1: 0.0
      lane_cost: 1.0
      offroad_cost: 10.0
      pedestrian_cost: 1000.0
      road_cost: -1.0
      road_green_cost: -10.0
      road_off_cost: 100.0
      road_on_cost: -10.0
      road_red_yellow_cost: 100.0
      steer_jerk: 1000.0
      vehicle_cost: 1000.0
    TURN:
      acceleration_jerk: 100.0
      action_difference: 100.0
      ego_location_l1: 1000.0
      ego_speed_l1: 0.0
      ego_yaw_l1: 0.0
      lane_cost: 1.0
      offroad_cost: 100.0
      pedestrian_cost: 1000.0
      road_cost: -1.0
      road_green_cost: -1.0
      road_off_cost: 100.0
      road_on_cost: -10.0
      road_red_yellow_cost: 5.0
      steer_jerk: -10.0
      vehicle_cost: 1000.0
  cost_weight_dropout: 0.0
  cost_weight_frames: 20
  init_action: random
  log_video: true
  log_video_scale: 0.1
  mpc_weight: 1.0
  num_optimization_iteration: 20
  repeat_frames: 1
  rollout_length: 20
  skip_frames: 5
experiment_type: eval_mpc_leaderboard
leaderboard:
  agent: /home/volkan/Documents/Codes/carla_env/leaderboard/leaderboard/autoagents/generic_algorithm_agent.py
  agent_config: /home/volkan/Documents/Codes/carla_env/configs/policy_model/testing/config.yml
  checkpoint: routes_testing_town_02_roach_cilrs_mpc_situational/Town02_route5.json
  debug: 1
  frame_rate: 0.1
  host: localhost
  port: 2000
  record: ''
  repetitions: 1
  resume: false
  routes: leaderboard/data/routes_testing_town_02/Town02_route5.xml
  scenarios: /home/volkan/Documents/Codes/carla_env/leaderboard/data/all_towns_traffic_scenarios_public.json
  timeout: '60'
  tm_port: 8000
  tm_seed: 2023
  track: MAP
log_path: null
num_time_step_future: 20
num_time_step_previous: 1
port: 2000
seed: 2023
tm_port: 8000
training:
  gradient_clip:
    enable: true
    type: norm
    value: 1.0
  optimizer:
    config:
      lr: 0.05
    type: Adam
wandb:
  enable: false
  group: test-mpc
  id: null
  link: null
  name: 1-10-10Hz-policy_cost-working-example
  notes: ''
  project: mbl-refactored
  resume: false
  resume_checkpoint_number: 0
wandb_ego_forward_model:
  checkpoint_number: 50
  link: vaydingul/mbl-refactored/5uei2p19
wandb_world_forward_model: null
