# TODO: Make it distributed with creating four different config files.

experiment_type: play_carla
log_path: ~

port: &port_var 2000
tm_port: &tm_port_var 8000

environment:
  name: carla_env_playground
  random: false
  action_repeat: 1
  fixed_delta_seconds: &dt 0.05
  max_steps: 50000
  port: *port_var
  tm_port: *tm_port_var
  tasks:
    - world: Town02
      num_vehicles: [90, 100]
      num_walkers: [50, 100]

  renderer:
    width: 1800
    height: 1000
    channel: 3
    background_color: [0, 0, 0]
    font_scale: 0.5
    font_color: [255, 255, 255]
    font_thickness: 1
    cursor: [0, 0]
    name: Play CARLA
    show: true
    save: true
    create_date_time_path: true
    save_path: figures/env_debug/play_carla/

  sensors:
    - id: rgb_front
      type: RGBSensor
      config:
        x: 1.5
        y: 0.0
        z: 2.4
        roll: 0.0
        pitch: 0.0
        yaw: 0.0
        width: 900
        height: 256
        fov: 100

    - id: rgb_left
      type: RGBSensor
      config:
        x: 1.5
        y: 0.0
        z: 2.4
        roll: 0.0
        pitch: 0.0
        yaw: 60.0
        width: 900
        height: 256
        fov: 100

    - id: rgb_right
      type: RGBSensor
      config:
        x: 1.5
        y: 0.0
        z: 2.4
        roll: 0.0
        pitch: 0.0
        yaw: -60.0
        width: 900
        height: 256
        fov: 100

    - id: ego
      type: VehicleSensor
      config: {}

    - id: occ
      type: OccupancySensor
      config:
        threshold: 3
        number_of_radars: 8
        horizontal_fov: 5
        vertical_fov: 5
        range: 10
        points_per_second: 100

    - id: imu
      type: IMUSensor
      config: {}

    - id: gnss
      type: GNSSSensor
      config: {}

    - id: radar_front_left
      type: RadarSensor
      config:
        x: 2.55
        y: 0.0
        z: 0.8
        roll: 0.0
        pitch: -5.0
        yaw: 60.0
        horizontal_fov: 35
        vertical_fov: 20
        range: 20
        points_per_second: 100

    - id: radar_front_right
      type: RadarSensor
      config:
        x: 2.55
        y: 0.0
        z: 0.8
        roll: 0.0
        pitch: -5.0
        yaw: -60.0
        horizontal_fov: 35
        vertical_fov: 20
        range: 20
        points_per_second: 100

    #! It is a must. NEVER DISCARD IT.
    - id: col
      type: CollisionSensor
      config: {}

  bevs:
    - id: "bev_world"
      config:
        width: 400
        height: 400
        render_lanes_on_junctions: false
        pixels_per_meter: 5
        crop_type: "FRONT_AREA_ONLY"
        road_on_off: true
        road_light: true
        light_circle: true
        lane_marking_thickness: 2

  noiser:
    type: GaussianNoiser
    config:
      mean: 0.0
      std: 0.1
wandb:
  enable: false
  resume: false
  resume_checkpoint_number: 0
  project: "mbl-refactored"
  group: "play-carla"
  name: ""
  id: ~
  notes: ""
