# @package _group_
entry_point: drivers.rl_birdview.models.ppo_policy_acmpc:PPO_ACMPC
kwargs:
  policy_head_arch: [256, 256]
  value_head_arch: [256, 256]
  features_extractor_entry_point: drivers.rl_birdview.models.torch_layers:XtMaCNN
  features_extractor_kwargs:
    states_neurons: [256, 256]
  distribution_entry_point: drivers.rl_birdview.models.distributions:DiagGaussianDistribution
  distribution_kwargs:
    dist_init: null
  mpc_entry_point: drivers.rl_birdview.models.mpc:ModelPredictiveControlWithoutOptimizer
  mpc_kwargs:
    system_entry_point: drivers.rl_birdview.models.torch_layers:CARLASystem
    system_kwargs: 
    cost_entry_point: drivers.rl_birdview.models.torch_layers:CARLACost
    cost_kwargs:
      device: cuda
      config:
        image_width: 256
        image_height: 256
        reduction: "sum"
        mask_alpha: 1.0
        decay_factor: 0.999
        vehicle_width: 2.0
        vehicle_length: 5.0
        pixels_per_meter: 10.0
        longitudinal_offset: 0.5
        longitudinal_scaler: 0.75
        longitudinal_speed_offset: 0.0
        longitudinal_speed_scaler: 1.0
        lateral_offset: 0.5
        lateral_scaler: 0.75
        lateral_speed_offset: 0.0
        lateral_speed_scaler: 0.1
    action_size: 2
    prediction_horizon: 10
    num_optimization_step: 10
    lr: 1.0
    std: 0.25
    device: cuda
  obs_to_state_target_fn: drivers.rl_birdview.utils.misc:obs_to_state_target
