experiment_type: test_policy_model
log_path: ~
seed: 999
port: &port_var 2000
tm_port: &tm_port_var 8000
num_time_step_previous: &previous 20
num_time_step_future: &future 10

environment:
  name: carla_env_testing_traffic
  random: false
  action_repeat: 1
  fixed_delta_seconds: &dt 0.05
  max_steps: 5000
  port: *port_var
  tm_port: *tm_port_var
  tasks:
    - world: Town02
      num_vehicles: 50
      num_walkers: 50
    # - world: Town03
    #   num_vehicles: [60, 90]
    # - world: Town04
    #   num_vehicles: [120, 180]
    # - world: Town06
    #   num_vehicles: [150, 300]

  renderer:
    width: 2800
    height: 1400
    channel: 3
    background_color: [0, 0, 0]
    font_scale: 0.25
    font_color: [255, 255, 255]
    font_thickness: 1
    cursor: [0, 0]
    name: Policy Model Testing
    show: true
    save: true
    create_date_time_path: true
    save_path: figures/env_debug/test_policy/

  sensors:
    - id: rgb_front
      type: RGBSensor
      config:
        x: 1.5
        y: 0.0
        z: 2.4
        roll: 0.0
        pitch: 0.0
        yaw: 0.0
        width: 900
        height: 256
        fov: 100

    - id: ego
      type: VehicleSensor
      config: {}

    - id: occ
      type: OccupancySensor
      config:
        threshold: 3
        number_of_radars: 8
        horizontal_fov: 5
        vertical_fov: 5
        range: 10
        points_per_second: 100

    #! It is a must. NEVER DISCARD IT.
    - id: col
      type: CollisionSensor
      config: {}

  bevs:
    - id: "bev_world"
      config:
        width: 192
        height: 192
        render_lanes_on_junctions: false
        pixels_per_meter: 5
        crop_type: "FRONT_AREA_ONLY"
        road_on_off: true
        road_light: true
        light_circle: true
        lane_marking_thickness: 2

  route:
    config:
      sampling_resolution: 20
      debug: true

tester:
  skip_frames: 1
  repeat_frames: 1
  rollout_length: *future
  log_video: false
  log_video_scale: 0.1

# wandb_ego_forward_model:
#   link: ""
#   checkpoint_number: 0

# wandb_world_forward_model:
#   link: ""
#   checkpoint_number: 0

wandb_policy_model:
  link: vaydingul/mbl-refactored/1w7jsf5g
  checkpoint_number: 47

wandb:
  enable: true
  resume: false
  resume_checkpoint_number: 0
  project: "mbl-refactored"
  group: "test-policy-model-20Hz"
  name: "20-10-20Hz"
  id: ~
  link: ~
  notes: ""
