experiment_type: "train_ego_forward_model"
seed: 42
checkpoint_path: "pretrained_models/"
log_path: ~ #"/home/volkan/Documents/Codes/carla_env/logs/"
num_time_step_previous: &previous 1
num_time_step_future: &future 10

# Dataset related parameters for training
dataset_train:
  data_path: "/home/volkan/Documents/Codes/carla_env/data/kinematic_model_train_data_10Hz"
  sequence_length: 11
  read_keys:
    - "ego"
  dilation: 2

# Dataloader related parameters for training
dataloader_train:
  batch_size: 100
  shuffle: true
  num_workers: 8

# Dataset related parameters for validation
dataset_val:
  data_path: "/home/volkan/Documents/Codes/carla_env/data/kinematic_model_val_data_10Hz"
  sequence_length: 11
  read_keys:
    - "ego"
  dilation: 2

# Dataloader related parameters for validation
dataloader_val:
  batch_size: 200
  shuffle: false
  num_workers: 8

# Training related parameters
training:
  learning_rate: 0.001
  num_epochs: 1000
  optimizer_type: "Adam"
  loss_criterion: "L1Loss"
  loss_reduction: "mean"
  loss_weight: ~
  save_interval: 50

# Ego forward model related parameters
ego_forward_model:
  dt: 0.2

# Wandb related parameters
wandb:
  enable: true
  resume: false
  resume_checkpoint_number: 0
  project: "mbl-refactored"
  group: "train-ego-forward-model-multi-step-5Hz"
  name: "1-10-5Hz"
  id: ~
  notes: "Ego forward model with 5Hz data and 10 time steps in the future. It can work with every model that works in 5Hz."
