experiment_type: dataset_weight
log_path: ~ #"logs/"

num_time_step_previous: &previous 0
num_time_step_future: &future 1
sequence_length: &sequence_length 1
num_workers: &num_workers 5
num_gpu: &num_gpu 1
batch_size: &batch_size 100
read_keys: &read_keys ["ego"]
dilation: &dilation 1

dataset:
  type: "InstanceDataset"
  config:
    data_path: "/mnt/kuacc/scratch/users/vaydingul20/driving_model_data_20Hz_action_repeat_1/train/"
    sequence_length: *sequence_length
    read_keys: *read_keys
    dilation: *dilation

weight_coefficients: [0.5, 0.5]
