config_path: "configs/world_forward_model/evaluation/config.yml"
save_path: &save_path "figures/world_forward_model_detailed_evaluation/"

wandbs:
  - link: vaydingul/mbl-refactored/1qr51yeg
    checkpoint_numbers: [5, 11, 17, 23, 29, 35, 41]
