seed: &seed_var 42
port: &port_var 2000
tm_port: &tm_port_var 8000

leaderboard:
  host: localhost
  port: *port_var
  tm_port: *tm_port_var
  tm_seed: *seed_var
  debug: 1
  record: ""
  timeout: "60"
  routes: /home/volkan/Documents/Codes/carla_env-2/carla_env/leaderboard_0.9.13/data/routes_town_2_debug_route_2.xml
  scenarios: /home/volkan/Documents/Codes/carla_env-2/carla_env/leaderboard_0.9.13/data/all_towns_traffic_scenarios_public.json
  repetitions: 1
  agent: /home/volkan/Documents/Codes/carla_env-2/carla_env/leaderboard_0.9.13/leaderboard/autoagents/model_agent.py
  agent_config: /home/volkan/Documents/Codes/carla_env-2/carla_env/configs/policy_model/testing/config.yml
  track: MAP
  resume: false
  checkpoint: "./results_town_2_route_2_repeat_2.json"
