# wandb_ego_forward_model:
#   link: ""
#   checkpoint_number: 0

# wandb_world_forward_model:
#   link: ""
#   checkpoint_number: 0

bev_agent_channel: &bev_agent_channel 7
bev_vehicle_channel: &bev_vehicle_channel 6
bev_selected_channels: &bev_selected_channels [0, 5, 6, 8, 9, 11]
bev_calculate_offroad: &bev_calculate_offroad false

wandb_policy_model:
  link: vaydingul/mbl-refactored/11vgz40s
  checkpoint_number: 47

evaluator:
  bev_agent_channel: *bev_agent_channel
  bev_vehicle_channel: *bev_vehicle_channel
  bev_selected_channels: *bev_selected_channels
  bev_calculate_offroad: *bev_calculate_offroad

bev:
  config:
    width: 192
    height: 192
    render_lanes_on_junctions: false
    pixels_per_meter: 5
    crop_type: "FRONT_AREA_ONLY"
    road_on_off: true
    road_light: true
    light_circle: true
    lane_marking_thickness: 2
