experiment_type: eval_policy_model_leaderboard
log_path: ~
seed: &seed_var 42
port: &port_var 2000
tm_port: &tm_port_var 8000
num_time_step_previous: &previous 20
num_time_step_future: &future 2

environment:
  name: carla_env_testing_traffic
  random: false
  action_repeat: 1
  fixed_delta_seconds: &dt 0.05
  max_steps: 5000
  port: *port_var
  tm_port: *tm_port_var
  tasks:
    - world: Town02
      num_vehicles: [60, 90]
    # - world: Town03
    #   num_vehicles: [60, 90]
    # - world: Town04
    #   num_vehicles: [120, 180]
    # - world: Town06
    #   num_vehicles: [150, 300]

  renderer:
    width: 2800
    height: 1400
    channel: 3
    background_color: [0, 0, 0]
    font_scale: 0.25
    font_color: [255, 255, 255]
    font_thickness: 1
    cursor: [0, 0]
    name: Policy Model Evaluation
    show: true
    save: false
    create_date_time_path: true
    save_path: figures/env_debug/eval_policy_leaderboard/

  sensors: []
  bevs: []

  route: ~

leaderboard:
  host: localhost
  port: *port_var
  tm_port: *tm_port_var
  tm_seed: *seed_var
  debug: 1
  record: ""
  timeout: "60"
  routes: /home/volkan/Documents/Codes/carla_env/leaderboard_0.9.13/data/routes_devtest.xml
  scenarios: /home/volkan/Documents/Codes/carla_env/leaderboard_0.9.13/data/all_towns_traffic_scenarios_public.json
  repetitions: 1
  agent: /home/volkan/Documents/Codes/carla_env/leaderboard_0.9.13/leaderboard/autoagents/model_agent.py
  agent_config: /home/volkan/Documents/Codes/carla_env/configs/policy_model/testing/config.yml
  track: MAP
  resume: false
  checkpoint: "./results.json"

wandb:
  enable: false
  resume: false
  resume_checkpoint_number: 0
  project: "mbl-refactored"
  group: "test-policy-model-20Hz"
  name: "20-10-20Hz"
  id: ~
  notes: ""
